# values
---

app:
  name: micromdm
  url: mdm.abaclock.ch

webhook:
  url: monitoring.abaclock.ch/post/mdm.php

build:
  ensure: false

acme:
  ensure: true
  owner: https://acme-v01.api.letsencrypt.org/acme/reg/31140065

replicaCount: 1
