image: golang:1.13.4

stages:
  - build
  - test

before_script:
  #- go get github.com/tools/godep
  # Don't use symlinks. Various tools like go test, etc. ignore symlinks
  #- cp -r /builds/user /go/src/github.com/user/
  # With alpine image we also need to do the following:
  #- apk add --update git
  #- cd /go/src/gitlab.com/${CI_PROJECT_PATH}
  
  # Fetch mods
  - go mod tidy
  
build:
  stage: build
  script:
    - make build

test:
  stage: test
  script:
    - make test
