version: 2
jobs:
  build-go1.11:
    docker:
        - image: golang:1.11
        - image: postgres:9.6
          environment:
            POSTGRES_DB: micromdm
            POSTGRES_USER: micromdm
            POSTGRES_PASSWORD: micromdm
        - image: mysql:5.7
          environment:
            - MYSQL_DATABASE=micromdm_test
            - MYSQL_USER=micromdm
            - MYSQL_PASSWORD=micromdm
            - MYSQL_ROOT_HOST=%
            - DB_HOST=127.0.0.1
            - DB_PORT=3306

    working_directory: /go/src/github.com/micromdm/micromdm
    steps: &steps
      - checkout
      - run: apt-get update -y && apt-get install postgresql-client -y
      - run: apt-get update -y && apt-get install mysql-client -y
      - run: make deps
      - run: GO111MODULE=on go install github.com/pressly/goose/cmd/goose
      - run: make db-reset-test
      - run: make db-migrate-test
      - run:
          name: Wait for DB
          # preinstalled in circleci/* docker image
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: MySQL version
          command: bundle exec ruby mysql_version.rb
      - run: make test
      - run: make


workflows:
  version: 2
  build:
    jobs:
      - build-go1.11
