version: 2
jobs:
  build-go1.11:
    docker:
        - image: golang:1.11
        - image: postgres:9.6
          environment:
            MICROMDM_RDBMS: postgres
            MICROMDM_RDBMS_DATABASE: micromdm_test
            MICROMDM_RDBMS_USERNAME: micromdm
            MICROMDM_RDBMS_PASSWORD: micromdm
            MICROMDM_RDBMS_HOST: 127.0.0.1
            MICROMDM_RDBMS_PORT: 5432
            POSTGRES_DB: micromdm
            POSTGRES_USER: micromdm
            POSTGRES_PASSWORD: micromdm
        - image: mysql:5.7
          environment:
            MICROMDM_RDBMS: mysql
            MICROMDM_RDBMS_DATABASE: micromdm_test
            MICROMDM_RDBMS_USERNAME: micromdm
            MICROMDM_RDBMS_PASSWORD: micromdm
            MICROMDM_RDBMS_HOST: 127.0.0.1
            MICROMDM_RDBMS_PORT: 3306
            MYSQL_ROOT_HOST: micromdm
            MYSQL_ROOT_PASSWORD: micromdm
            MYSQL_DATABASE: micromdm_test
            MYSQL_USER: micromdm
            MYSQL_PASSWORD: micromdm

    working_directory: /go/src/github.com/micromdm/micromdm
    steps: &steps
      - checkout
      - run: apt-get update -y && apt-get install postgresql-client -y
      - run: apt-get update -y && apt-get install default-mysql-client -y
      - run: make deps
      - run: GO111MODULE=on go install github.com/pressly/goose/cmd/goose
      - run:
          name: Waiting for MySQL to be ready
            command: |
              for i in `seq 1 10`;
              do
                nc -z 127.0.0.1 3306 && echo Success && exit 0
                echo -n .
                sleep 1
              done
              echo Failed waiting for MySQL && exit 1
      - run: make db-reset-test
      - run: make db-migrate-test
      - run: make test
      - run: make


workflows:
  version: 2
  build:
    jobs:
      - build-go1.11
